[package]
name = "n7"
version = "0.1.0"
authors = ["Don Luchini <don-code@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.11"
